services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase # Name of the database to create
      POSTGRES_USER: myuser # User for the database
      POSTGRES_PASSWORD: mypassword # Password for the user
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      NODE_ENV: production
    ports:
      - "4949:4949"
  react-app:
    build:
      context: ./front
    depends_on:
      - backend
    ports:
      - "3000:80" # Redirect port 3000 to 80
    restart: unless-stopped
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8081:8080"  # Jenkins UI
      - "50000:50000" # For Jenkins agent
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin_password
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Disable setup wizard (optional)

volumes:
  postgres_data:
