services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - "4949:4949"
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8081:8080"  # Jenkins UI
      - "50000:50000" # For Jenkins agent
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin_password
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Disable setup wizard (optional)