services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 4949:4949
  react-app:
    build:
      context: ./front
    ports:
      - "3000:80" # Redirect port 3000 to 80
    restart: unless-stopped
