services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase       # Name of the database to create
      POSTGRES_USER: myuser          # User for the database
      POSTGRES_PASSWORD: mypassword  # Password for the user
    ports:
      - "5432:5432"                  # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
  backend:
    build:
      context: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
    ports:
      - 4949:4949

volumes:
  postgres_data:
