### Get all users
GET http://localhost:4949/api/users

### Create a new user
POST http://localhost:4949/api/users
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@example.com"
}

